version: '3'

services:
  root-app:
    image: singlespasample/root-app
    ports:
      - 80:80

  ember-app:
    image: singlespasample/ember-app
    ports:
      - 4201:80

  react-app:
    image: singlespasample/react-app
    ports:
      - 8081:80

  backend:
    image: singlespasample/backend
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 6501:80

  app-postgres-db:
    image: singlespasample/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
volumes:
  DB:
